
services:
    api: 
        build:
            context: .
        volumes:
            - .:/backend
        env_file:
            - .env
        ports:
            - '8000:8000'
        command: sh runserver.sh 
        depends_on:
            - database
        networks:
            - service-network
        entrypoint: 
    
    database: 
        image: postgres:14.6-alpine
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - '5432:5432'
        networks:
            - service-network

networks:
    service-network: 
        driver: bridge
    

    
